### ISSUE TITLE
[Tracking] Extended Downtime

### ISSUE THREAD

**Issue by meissadia** [cfpb/hmda-frontend#1060]
## Frontend Maintenance PRs
- [x] https://github.com/cfpb/hmda-frontend/pull/1089
- [x] https://github.com/cfpb/hmda-frontend/pull/1090
- [x] https://github.com/cfpb/hmda-frontend/pull/1091
- [x] https://github.com/cfpb/hmda-frontend/pull/1092
- [x] https://github.com/cfpb/hmda-frontend/pull/1093

## Prep for maintenance
- [x] Enable multiple announcements to be added in the external config "announcement" key (#1074)
- [x] ^^ Deploy changes ^^
- [x] Post a banner on the Platform homepage to announce extended downtime (#1077).
- [x] Post a banner on the Filing homepage to announce extended downtime (#1077).

## During maintenance
- [x] Post a banner on the homepage that maintenance is in progress (ext config => announcements)
- [x] Block access to the Filing application during downtime (maintenance mode => true)
- [x] Post a banner on the filing app that maintenance is in progress (ext config => filingAnnouncement)
 
## Maintenance validation testing
- [x] Keep banners on the homepage/filing that maintenance is in progress
- [x] Enable access to the Filing application (maintenance mode => false)
- [x] Perform integration testing

## Post-maintenance
- [x] Remove banners
  - [x] ext config => announcements
  - [x] ext config => filingAnnouncement
- [x] Ensure filing app is enabled
- ~~Verify that '2021-Q3 is open' announcement banner is up~~
