### ISSUE TITLE
Go-Live - 2021 Data Publication

### ISSUE THREAD

**Issue by meissadia** [cfpb/hmda-frontend#1442]
## Tasks
- [ ] Announce 2021 publication release
- [ ] Announce data browser datasource update?
- [ ] Prune current list of announcements
- [ ] Add entry to `Updates & Notes`
- [ ] Update production config with available publication years
- [ ] Do we want to make this the announcement on the Filing homepage?

## Proposed publications announcement
<img width="1016" alt="pubs-announcement" src="https://user-images.githubusercontent.com/2592907/171946744-6df11aa0-9c24-4a42-98e9-9f19fc2c4f19.png">

```json
    {
      "heading": "2021 Data Publication Release",
      "message": "On June xx, 2022, the 2021 static datasets, Disclosure Reports, and MSA/MD Aggregate reports were released and can be accessed via the ",
      "type": "info",
      "link": {
        "url": "https://ffiec.cfpb.gov/data-publication/",
        "text": "Data Publications page."
      }
    },
```
 
## Proposed `Updates and Notes` entries
<img width="1122" alt="mock-updates" src="https://user-images.githubusercontent.com/2592907/172261331-2277f030-0185-41d8-b823-3eac976c2203.png">
