### ISSUE TITLE
[Tools] Online LARFT tool production checklist

### ISSUE THREAD

**Issue by Michaeldremy** [cfpb/hmda-frontend#1776]
Ticket created to keep a checklist of tasks to complete for making the Online LARFT tool to be added to the existing tools.

Pre-production tasks:
- [x] Update OLARFT documentation to be `online-lar-formatting` name to resolve conflicts with existing excel `lar-formatting` tool.
- [x] Update OLARFT route to be `online-lar-formatting`
- [x] Update HMDA Homepage to discuss new release of the OLARFT tool
- [x] Update route on the OLARFT Homepage to point to the correct documentation
- [x] Add back the documentation for the `lar-formatting` tool.
- [x] Add OLARFT to documentation page under `/documentation/2023/tools/lar-formatting/`
- [x] Add OLARFT to the documentation homepage under the tools section
- [x] Add OLARFT as a new tool under the `/tools` route
- [x] Re-write header for the OLARFT Homepage - _Pending comments from the team_

Other tasks related to OLARFT: 
- [x] Add OLARFT Markdown doc to Docusaurus
- [x] Update [Docusaurus Prod Ready](https://github.com/cfpb/hmda-combined-documentation/tree/prod-markdown-url-updates) branch to handle redirect
