### ISSUE TITLE
Meta Maps & Graphs Feature Updates

### ISSUE THREAD

**Issue by chynnakeys** [cfpb/hmda-frontend#763]
Prior to next week's presentation, we should make a few updates to the maps & graphs feature:

- [x] Default year to 2019
- [ ] Change the name of the feature from Maps & Graphs to Data Visualizations (we can discuss the name)
- [ ] Updated descriptions (to be provided)
- [ ] Having the map selection not dropdown to the table upon selecting an area on the map (it automatically takes you to the table upon selecting a state/county)
- [ ] Grey out value (steps 3 & 5) until a variable is selected 

- [ ] Michigan's data is available in the table, but not showing up on the map. This has happened from multiple queries. Ex: 
![image](https://user-images.githubusercontent.com/41752348/100119035-70335c00-2e44-11eb-9925-eb5771ad93b6.png)

**Comment by wpears** [comment]
Did the first checkbox in https://github.com/cfpb/hmda-frontend/pull/764

Not having the map selection move down was a problem before because people would make a selection and not realize a table had appeared or that they could download data. If moving them to the table is too disruptive, we could perhaps instead include a link in the popup that says "View Table" which would scroll the screen on click. We'd have to rework the popup logic a bit to support this, making popups stick when the user clicks (and possibly make the dismissible with a close button).

I played around with greying out step 3 and 5 before their associated variables were selected, but it felt more visually confusing to me. Definitely fine with trying this approach again.

**Comment by chynnakeys** [comment]
Thanks, Wyatt! We can perhaps discuss this more at standup. I just found that it seemed a bit bothersome to the user that anytime they selected an area, it automatically went down to the bottom of the screen. Would there be a way to show just the map and table? I feel like it's a pretty drastic jump to not see any of the map. 

& regarding the greying out, we found that a user tried to select from step 3 without selecting a variable from step 2 ad was confused. It may be something we can work on in the future if we don't find it that disruptive to others.

**Comment by chynnakeys** [comment]
@meissadia 

Updated description to this page:

![image](https://user-images.githubusercontent.com/41752348/100940927-cea4ae00-34c6-11eb-9b7a-00ddc0c1f7c1.png)


The Map tool gives you the opportunity to visualize cross-selections of HMDA Data variables. For questions/suggestions, contact hmdahelp@cfpb.gov.

Can we also use the small text in Step 3 of dataset filtering 

![image](https://user-images.githubusercontent.com/41752348/100940858-b59bfd00-34c6-11eb-80d9-eed2e749ee42.png)

to replace the text in the Step 2 of maps and graphs?

![image](https://user-images.githubusercontent.com/41752348/100941054-fdbb1f80-34c6-11eb-8ed6-5fe0d280205e.png)

**Comment by meissadia** [comment]
@chynnakeys Updates are deployed to Dev-Beta.

PR: https://github.com/cfpb/hmda-frontend/pull/781
