### ISSUE TITLE
Update Dependencies

### ISSUE THREAD

**Issue by meissadia** [cfpb/hmda-frontend#828]
- [x] [Snyk] Upgrade file-saver from 2.0.2 to 2.0.5 #790
- [x] [Snyk] Upgrade keycloak-js from 11.0.2 to 11.0.3 #771
- [x] [Snyk] Upgrade csv-parse from 4.12.0 to 4.13.1 #770
- [x] [Snyk] Upgrade react-window from 1.8.5 to 1.8.6 #757
- [x] [Snyk] Upgrade react-redux from 7.2.1 to 7.2.2 #751

**Comment by meissadia** [comment]
All package updates already applied, the above are just old tickets that didn't get closed.
