### ISSUE TITLE
Update Dependencies

### ISSUE THREAD

**Issue by meissadia** [cfpb/hmda-frontend#834]
- [x] [Snyk] Upgrade react-scripts from 4.0.0 to 4.0.1 #833
- [x] [Snyk] Upgrade react-select from 3.1.0 to 3.1.1 #832
- [x] [Snyk] Upgrade mapbox-gl from 1.12.0 to 1.13.0 #831
- [x] [Snyk] Upgrade csv-parse from 4.13.1 to 4.14.2 #830
