### ISSUE TITLE
Update Dependencies

### ISSUE THREAD

**Issue by meissadia** [cfpb/hmda-frontend#873]
- [x] Libraries
  - [x] Bump react-dev-utils from 11.0.1 to 11.0.4 #872
  - [x] [Snyk] Upgrade mapbox-gl from 1.13.0 to 1.13.1 #871
  - [x] Bump elliptic from 6.5.3 to 6.5.4 #870
  - [x] [Snyk] Upgrade react-scripts from 4.0.1 to 4.0.2 #861
  - [x] [Snyk] Upgrade csv-parse from 4.15.0 to 4.15.1 #853
  - [x] [Snyk] Upgrade react-highlight-words from 0.16.0 to 0.17.0 #849
  - [x] https://www.npmjs.com/package/cypress 6.6.0
  - [x] [Snyk] Upgrade csv-parse from 4.15.0 to 4.15.3 #880
  - [x] [Snyk] Upgrade react-scripts from 4.0.1 to 4.0.3 #881
-  [x] Rebuild and deploy Cypress testing image
